### PR TITLE
fix: Fixed delegated pda only with rent exempt balance

### LINKED ISSUE #33: Bug: delegation of PDA result in only rent exempt balance
## Description

The delegation of PDAs result in a delegate account with only rent exempt balance. If lamports > rent exception, the lamports are currently returned to the payer.

## Expected behaviour

Expected behaviour is that the PDA is delegated with the actual lamports value

### PR DESCRIPTION
**Pull request by notdanilo**
Closes #33

### CODE REVIEW

**Review by GabrielePicco — APPROVED** [review]
lgtm. 
We could optimize by zeoring the data and avoid PDA closing/re-opening, but could be a follow-up PR.

File: rust/resolver/src/error.rs [hunk 1]
```diff
@@ -13,7 +13,7 @@ pub enum Error {
     HttpClient(#[from] reqwest::Error),
     /// Error making rpc request via solana client
     #[error("solana rpc-client error: {0}")]
-    Rpc(#[from] client_error::Error),
+    Rpc(#[from] Box<client_error::Error>),
```
Comment (GabrielePicco) [inline rust/resolver/src/error.rs:16]: Q: why this change was needed?

**Review by GabrielePicco — APPROVED** [review]
lgtm, more efficient

File: rust/resolver/src/error.rs (hunk 1 above)
Comment (notdanilo) [reply rust/resolver/src/error.rs:16]: @GabrielePicco because this variant is too big https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
